services:
  contact-form:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: contact-form-app
    env_file:
      - .env
    ports:
      - "3006:3006"
    restart: unless-stopped
